spring:
  datasource:
    url: jdbc:h2:mem:MASTNAILDB;INIT=CREATE SCHEMA IF NOT EXISTS MASTNAILDB;DB_CLOSE_DELAY=-1
    username: sa
    driver-class-name: org.h2.Driver
    hikari:
      schema: MASTNAILDB
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8081
